export const AUTH_ACTION_TYPES = {
    AUTH_START: "auth/AUTH_START",
    AUTH_SUCCESS: "auth/AUTH_SUCCESS",
    AUTH_FAILED: "auth/AUTH_FAILED",

    LOG_OUT: "auth/LOG_OUT",

    UPDATING_START: "auth/UPDATING_START",
    UPDATING_SUCCESS: "auth/UPDATING_SUCCESS",
    UPDATING_FAILED: "auth/UPDATING_FAILED",

    FOLLOW_USER: "auth/FOLLOW_USER",
    UNFOLLOW_USER: "auth/UNFOLLOW_USER",

}