export const POST_ACTION_TYPES = {
    UPLOAD_START: "post/UPLOAD_START",
    UPLOAD_SUCCESS: "post/UPLOAD_SUCCESS",
    UPLOAD_FAIL: "post/UPLOAD_FAIL",

    RETREIVING_START: "post/RETREIVING_START",
    RETREIVING_SUCCESS: "post/RETREIVING_SUCCESS",
    RETREIVING_FAIL: "post/RETREIVING_FAIL",

    DELETE_START: "post/DELETE_START",
    DELETE_SUCCESS: "post/DELETE_SUCCESS",
    DELETE_FAIL: "post/DELETE_FAIL",

    COMMENT_START: "post/COMMENT_START",
    COMMENT_SUCCESS: "post/COMMENT_SUCCESS",
    COMMENT_FAIL: "post/COMMENT_FAIL"
}